### ISSUE TITLE
Branch picker always redirects to http:

### ISSUE THREAD

**Issue by robertjsullivan** [pivotal/mkdocs-pivotal-theme#4]
The branch picker on our site will always redirect to http even when the originating URL was in https

Please fix the picker to respect protocol that is in use.  

Steps to reproduce:

Navigate to: https://docs.pivotal.io/reliability-view/master/ , verify that the URL is secured, then select "master" again from the picker and verify that the URL is unsecured.

![Screenshot 2019-06-27 11 18 44](https://user-images.githubusercontent.com/1566115/60286987-c6623f80-98de-11e9-9b19-d7923d20b8c1.png)

**Comment by jtarchie** [comment]
@robertjsullivan this should be fixed. Re-deploy your apps. Let me know.
